default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILES_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") { 'root' } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { 'password' } %>
  host: db

development:
  <<: *default
  database: remote-work-space_development

test:
  <<: *default
  database: remote-work-space_test

production:
  <<: *default
  host: remote-work-space-db.c5vzectdhrxx.ap-northeast-1.rds.amazonaws.com
  database: remote-work-space_production
  username: db_user
  password: db_password
